### ISSUE TITLE
negative evaluations in the final report

### ISSUE THREAD

**Issue by napo** [CarloRamponi/TrainingStats#6]
include negative evaluation  (=) in the final report

**Comment by CarloRamponi** [comment]
I'm not sure if I got it, you mean a table just for negative actions?
Because in the upcoming update there is the table in which there will be all negative "losing" actions and positive "winning" ones (see screenshots) 
![Screenshot_1603099211](https://user-images.githubusercontent.com/11007482/96426191-32b43100-11fd-11eb-9d1d-cbdd58aba3d0.png)
![Screenshot_1603099215](https://user-images.githubusercontent.com/11007482/96426195-334cc780-11fd-11eb-821c-340d297b0a56.png)

**Comment by CarloRamponi** [comment]
I have also included this table:
![Screenshot_1603103667](https://user-images.githubusercontent.com/11007482/96439970-93486b80-1207-11eb-94de-00b41f46794d.png)
![Screenshot_1603103706](https://user-images.githubusercontent.com/11007482/96439973-93e10200-1207-11eb-8823-7d34aff6bbd6.png)

Is it enough?

**Comment by napo** [comment]
OK!
Now is ok!
In my report wasn't present the negative scores.
Maybe an old version?

**Comment by CarloRamponi** [comment]
Solved in b9a4e2d83f692025cfd6b7fa4c0c5b7d5e02af50
